version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: marsbots
      MONGO_INITDB_ROOT_PASSWORD: marsbots
    networks:
      - app-tier
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: marsbots
      ME_CONFIG_MONGODB_ADMINPASSWORD: marsbots
      ME_CONFIG_MONGODB_URL: mongodb://marsbots:marsbots@mongo:27017/
    networks:
      - app-tier
    profiles:
      - dev

  bots:
    depends_on:
      - mongo
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
